server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order-service
  kafka:
    listener:
      missing-topics-fatal: false
    bootstrap-servers:
      #- localhost:9091
      - localhost:9092
      #- localhost:9093
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.LongDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer